name: homie

services:
  homie-postgres:
    container_name: homie-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - homie-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 3

  homie-mailpit: # For sending email in development
    container_name: homie-mailpit
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  homie-postgres-data:
