name: Deploy Preview

on:
  pull_request:
    types:
      - opened
      - reopened

env:
  ORG_NAME: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.event.repository.name }}
  BRANCH_NAME: ${{ github.head_ref }}
  COMPOSE_PATH: './docker/compose.prod.yaml'
  APP_NAME: pr-${{ github.event.number }}-${{ github.event.repository.name }}

jobs:
  deploy-preview:
    name: Deploy Preview
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Generate secrets
        id: generate-secrets
        run: |
          echo "POSTGRES_PASSWORD=$(LC_CTYPE=C tr -d -c '[:alnum:]' </dev/urandom | head -c 15)" >> $GITHUB_ENV
          echo "POSTGRES_PORT=$(shuf -i 55000-55999 -n 1)" >> $GITHUB_ENV
          echo "AUTH_SECRET=$(openssl rand -base64 32)" >> $GITHUB_ENV

      - name: Convert Env String
        id: convert-env
        run: |
          ENV_STRING_RAW=$(cat << 'EOF'
          POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}
          POSTGRES_PORT=${{ env.POSTGRES_PORT }}
          AUTH_SECRET=${{ env.AUTH_SECRET }}
          AUTH_URL=https://${{ env.APP_NAME }}.sieutoc.app
          POSTMARK_API_KEY=${{ '${{project.POSTMARK_API_KEY}}' }}
          FROM_EMAIL=${{ '${{project.FROM_EMAIL}}' }}
          OPENAI_API_KEY=${{ '${{project.OPENAI_API_KEY}}' }}
          OPENAI_API_BASE_URL=${{ '${{project.OPENAI_API_BASE_URL}}' }}
          OPENAI_MODEL=${{ '${{project.OPENAI_MODEL}}' }}
          EOF
          )
          ENV_STRING_ESCAPED="${ENV_STRING_RAW//$'\n'/\\n}"
          echo "env_string=${ENV_STRING_ESCAPED}" >> $GITHUB_OUTPUT

      - name: Create New Compose
        run: |
          CREATED_RESPONSE=$(curl -X POST "${{ vars.DOKPLOY_URL }}/api/compose.create" \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "name": "${{ env.APP_NAME }}",
            "projectId": "${{ vars.PROJECT_ID }}",
            "appName":"${{ env.APP_NAME }}",
            "composeType": "docker-compose",
            "serverId": null
          }')
          echo "COMPOSE_ID=$(echo $CREATED_RESPONSE | jq -r '.composeId')" >> $GITHUB_ENV

      - name: Update Compose
        run: |
          curl -X POST '${{ vars.DOKPLOY_URL }}/api/compose.update' \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "composeId":"${{ env.COMPOSE_ID }}",
            "env": "${{ steps.convert-env.outputs.env_string }}",
            "composePath":"${{ env.COMPOSE_PATH }}",
            "githubId":"${{ vars.NODE_GITHUB_ID }}",
            "branch":"${{ env.BRANCH_NAME }}",
            "repository":"${{ env.REPO_NAME }}",
            "owner":"${{ env.ORG_NAME }}",
            "sourceType":"github",
            "composeStatus":"idle"
          }'

      - name: Create New Domain
        run: |
          curl -X POST '${{ vars.DOKPLOY_URL }}/api/domain.create' \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "host": "${{ env.APP_NAME }}.sieutoc.app",
            "path": "/",
            "port": 3000,
            "https": true,
            "applicationId": null,
            "certificateType": "letsencrypt",
            "composeId": "${{ env.COMPOSE_ID }}",
            "serviceName": "${{ env.REPO_NAME }}-nextjs",
            "domainType": "compose"
          }'

      - name: Deploy Compose
        run: |
          curl -X POST '${{ vars.DOKPLOY_URL }}/api/compose.deploy' \
          -H "x-api-key: ${{ secrets.DOKPLOY_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "composeId":"${{ env.COMPOSE_ID }}"
           }'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Deploy Migrations
        run: pnpm prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:${{ env.POSTGRES_PASSWORD }}@server.sieutoc.app:${{ env.POSTGRES_PORT }}/postgres?schema=public

      - name: Seed Database
        run: pnpm prisma db seed

      - name: Comment Preview URL
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              🚀 Preview environment deployed successfully!
              👉 Access your preview at: https://${{ env.APP_NAME }}.sieutoc.app
              `
            })
